# Generated by Django 6.1 on 2026-09-05 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clinics', '0004_delete_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChangerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_plan', models.CharField(choices=[('standard', 'Standard (1 doctor, 1 secretary)'), ('pay_per_visit', 'Pay per visit')], max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('ccp', 'CCP (Algérie Poste)')], max_length=20)),
                ('proof_file', models.FileField(upload_to='billing/payment_proofs/%Y/%m/')),
                ('reference_note', models.CharField(blank=True, help_text='Optional — transfer reference number, sender name, or other note to help matching.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to='clinics.clinic')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plan_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
