# Generated by Django 6.1 on 2026-09-06 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_planchangerrequest'),
        ('clinics', '0004_delete_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanChangerRequest',
            new_name='PlanChangeRequest',
        ),
    ]
