# Generated by Django 6.1 on 2026-09-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_planchangerrequest_planchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_rib', models.CharField(blank=True, max_length=100, verbose_name='Bank RIB')),
                ('ccp_number', models.CharField(blank=True, max_length=100, verbose_name='CCP number')),
                ('ccp_key', models.CharField(blank=True, max_length=20, verbose_name='CCP key')),
                ('additional_notes', models.TextField(blank=True, help_text="Any extra instructions shown to clinic-admins (e.g. 'include your clinic name in the transfer reference').")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment instructions',
                'verbose_name_plural': 'Payment instructions',
            },
        ),
    ]
