# Generated by Django 6.1 on 2026-09-06 11:58

import billing.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_paymentinstructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchangerequest',
            name='proof_file',
            field=models.FileField(help_text='PDF or image (JPG/PNG), max 5MB.', upload_to='billing/payment_proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), billing.models.validate_proof_file_size]),
        ),
    ]
