# Generated by Django 6.1 on 2026-08-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='professional_email',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='professional_title',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='stamp',
        ),
    ]
