# Generated by Django 6.1 on 2026-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
