from decimal import Decimal

TRIAL_DAYS = 14
TRIAL_PATIENT_LIMIT = 50

STANDARD_MONTHLY_PRICE = Decimal("10000.00")
STANDARD_DOCTOR_LIMIT = 1
STANDARD_SECRETARY_LIMIT = 1

PAY_PER_VISIT_PRICE = Decimal("50.00")