# Generated by Django 6.1 on 2026-08-24 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_delete_patient'),
        ('patients', '0003_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDocumentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='doctors/signatures/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='doctors/stamps/')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_profile', to='clinics.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinics.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='records.prescription')),
            ],
        ),
    ]
