# Generated by Django 6.1 on 2026-09-02 11:19

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_labworkdemand_labworkitem_procedurereport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornote',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='labworkitem',
            name='clinical_indication',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.AlterField(
            model_name='labworkitem',
            name='test_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100)),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100)),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100)),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medication_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='findings',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='procedure_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='procedurereport',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
    ]
