# Generated by Django 6.1 on 2026-09-05 20:58

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_doctornote_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_name_override',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text="Optional. Overrides the patient's name on this prescription only — does not change the patient's actual record.", max_length=300)),
        ),
    ]
