# Generated by Django 6.1 on 2026-08-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='approximate_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Only used when exact date of birth isn't known/given", null=True),
        ),
    ]
