# Generated by Django 6.1 on 2026-09-02 11:19

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_approximate_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
    ]
